-- =====================================================
-- LETELIER - SEED (MERGE ONLY, SIN COLUMNA ID) PARA H2
-- Motivo: En H2, incluir la columna ID (IDENTITY) en MERGE fuerza DEFAULT/NULL
-- y puede romper con 'NULL not allowed for column "ID"'. Se omite ID para que
-- el INSERT use el autoincrement y el UPDATE preserve el ID existente.
-- =====================================================

-- ========== PACIENTES ==========
MERGE INTO PATIENT (NOMBRES, APELLIDOS, RUT, FECHA_NAC, TELEFONO, EMAIL, DIRECCION, ACTIVO)
KEY (RUT) VALUES ('Juan', 'Rojas', '12.345.678-9', DATE '1990-05-10', '987654321', 'juan.rojas@example.com', 'Av. Central 123', TRUE);

MERGE INTO PATIENT (NOMBRES, APELLIDOS, RUT, FECHA_NAC, TELEFONO, EMAIL, DIRECCION, ACTIVO)
KEY (RUT) VALUES ('Maria', 'Perez', '9.876.543-2', DATE '1988-09-22', '912345678', 'maria.perez@example.com', 'Calle Norte 456', TRUE);

-- ========== OPERATIVOS ==========
MERGE INTO OPERATIVE (NOMBRE, LUGAR, DIRECCION, FECHA, OBSERVACIONES, ACTIVO)
KEY (NOMBRE, FECHA) VALUES ('Operativo Plaza', 'Plaza Central', 'Plaza 1, Comuna', DATE '2025-09-12', 'Jornada AM', TRUE);

MERGE INTO OPERATIVE (NOMBRE, LUGAR, DIRECCION, FECHA, OBSERVACIONES, ACTIVO)
KEY (NOMBRE, FECHA) VALUES ('Operativo Sur', 'Sede Sur', 'Av. Sur 987', DATE '2025-09-13', 'Jornada PM', TRUE);

-- ========== RELACIÓN Paciente-Operativo ==========
MERGE INTO PATIENT_OPERATIVE (PATIENT_ID, OPERATIVE_ID)
KEY (PATIENT_ID, OPERATIVE_ID)
VALUES (
  (SELECT MIN(ID) FROM PATIENT   WHERE RUT='12.345.678-9'),
  (SELECT MIN(ID) FROM OPERATIVE WHERE NOMBRE='Operativo Plaza' AND FECHA=DATE '2025-09-12')
);

-- ========== RECETAS ==========
MERGE INTO PRESCRIPTION (PACIENTE_ID, OD_ESFERA, OD_CILINDRO, OD_EJE, OI_ESFERA, OI_CILINDRO, OI_EJE, ADD_POWER, OBSERVACIONES, FECHA, ACTIVO)
KEY (PACIENTE_ID, FECHA, OBSERVACIONES)
VALUES (
  (SELECT MIN(ID) FROM PATIENT WHERE RUT='12.345.678-9'),
  -1.25, -0.50, 90, -1.00, -0.25, 80, 2.00,
  'Lentes de lectura',
  DATE '2025-09-12',
  TRUE
);

MERGE INTO PRESCRIPTION (PACIENTE_ID, OD_ESFERA, OD_CILINDRO, OD_EJE, OI_ESFERA, OI_CILINDRO, OI_EJE, ADD_POWER, OBSERVACIONES, FECHA, ACTIVO)
KEY (PACIENTE_ID, FECHA, OBSERVACIONES)
VALUES (
  (SELECT MIN(ID) FROM PATIENT WHERE RUT='9.876.543-2'),
  -0.75, -0.25, 85, -0.50, -0.25, 95, NULL,
  'Uso diario',
  DATE '2025-09-12',
  TRUE
);

-- ========== BOLETAS (INVOICE) ==========
MERGE INTO INVOICE (PACIENTE_ID, PRESCRIPTION_ID, FECHA, TOTAL, DETALLE, ANULADO)
KEY (PACIENTE_ID, FECHA, TOTAL, DETALLE)
VALUES (
  (SELECT MIN(ID) FROM PATIENT WHERE RUT='12.345.678-9'),
  (SELECT MIN(ID) FROM PRESCRIPTION WHERE PACIENTE_ID=(SELECT MIN(ID) FROM PATIENT WHERE RUT='12.345.678-9')),
  DATE '2025-09-12',
  35000,
  'Armazon basico + cristales monofocales',
  FALSE
);
